from __future__ import annotations
import json, subprocess, os, sys, shutil
from pathlib import Path
from .registry import Registry, Tool
from ..settings import Settings


PROJECT_TEMPLATES = {
    "next-app":   ["npx", "create-next-app@latest", "{name}", "--ts", "--app", "--tailwind", "--eslint", "--src-dir", "--import-alias", "@/*", "--no-git"],
    "vite-react": ["npm", "create", "vite@latest", "{name}", "--", "--template", "react-ts"],
    "vite-vue":   ["npm", "create", "vite@latest", "{name}", "--", "--template", "vue-ts"],
    "sveltekit":  ["npm", "create", "svelte@latest", "{name}"],
    "astro":      ["npm", "create", "astro@latest", "{name}"],
    "nuxt":       ["npx", "nuxi@latest", "init", "{name}"],
    "nestjs":     ["npx", "@nestjs/cli", "new", "{name}", "--package-manager", "npm", "--skip-git"],
    "express":    [],
    "fastapi":    [],
    "flask":      [],
    "django":     ["django-admin", "startproject", "{name}"],
    "cargo-bin":  ["cargo", "new", "{name}"],
    "cargo-lib":  ["cargo", "new", "--lib", "{name}"],
    "go-mod":     [],
    "tauri":      ["npm", "create", "tauri-app@latest", "{name}"],
    "electron":   ["npx", "create-electron-app@latest", "{name}"],
    "expo":       ["npx", "create-expo-app@latest", "{name}"],
}


def _gitignore(template: str) -> str:
    base = [
        "# Generated by coder-agent", ".env", ".env.local", ".DS_Store",
        "node_modules/", "dist/", "build/", "coverage/", ".cache/",
        "*.log", "*.swp",
    ]
    if template.startswith(("fastapi", "flask", "django")):
        base += ["__pycache__/", ".venv/", "venv/", "*.pyc", ".pytest_cache/", ".mypy_cache/"]
    if template.startswith("cargo"):
        base += ["target/", "Cargo.lock"]
    return "\n".join(base) + "\n"


def register(r: Registry, s: Settings) -> None:

    def scaffold_project(template: str, name: str, cwd: str = ".") -> str:
        if template not in PROJECT_TEMPLATES:
            return json.dumps({"ok": False, "error": f"unknown template: {template}. Available: {list(PROJECT_TEMPLATES)}"})
        working = (s.workdir / cwd).resolve()
        working.mkdir(parents=True, exist_ok=True)

        cmd = PROJECT_TEMPLATES[template]
        target = working / name

        if cmd:
            filled = [p.replace("{name}", name) for p in cmd]
            try:
                out = subprocess.run(filled, cwd=working, capture_output=True, text=True, timeout=600)
                if out.returncode != 0:
                    return json.dumps({"ok": False, "stderr": out.stderr[-2000:]})
            except subprocess.TimeoutExpired:
                return json.dumps({"ok": False, "error": "timeout"})
        else:
            target.mkdir(parents=True, exist_ok=True)
            _bootstrap_manual(template, target)

        (target / ".gitignore").write_text(_gitignore(template))
        return json.dumps({"ok": True, "path": str(target), "template": template})

    def init_venv(path: str = ".", python: str = "python3") -> str:
        p = (s.workdir / path).resolve()
        out = subprocess.run([python, "-m", "venv", ".venv"], cwd=p, capture_output=True, text=True)
        return json.dumps({"ok": out.returncode == 0, "stderr": out.stderr})

    def create_env_file(path: str, vars: dict[str, str]) -> str:
        p = (s.workdir / path).resolve()
        p.parent.mkdir(parents=True, exist_ok=True)
        content = "\n".join(f"{k}={v}" for k, v in vars.items()) + "\n"
        p.write_text(content)
        example = p.parent / f"{p.name}.example"
        example.write_text("\n".join(f"{k}=" for k in vars) + "\n")
        return json.dumps({"ok": True, "env": str(p), "example": str(example)})

    def create_dockerfile(path: str, stack: str) -> str:
        p = (s.workdir / path).resolve() / "Dockerfile"
        content = _dockerfile_template(stack)
        if content is None:
            return json.dumps({"ok": False, "error": f"unknown stack {stack}"})
        p.write_text(content)
        return json.dumps({"ok": True, "path": str(p)})

    def create_github_workflow(path: str, provider: str = "github") -> str:
        p = (s.workdir / path).resolve() / ".github" / "workflows" / "ci.yml"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(_gh_workflow())
        return json.dumps({"ok": True, "path": str(p)})

    for t in [
        Tool("scaffold_project", "Create a new project from a template (next-app, vite-react, fastapi, cargo-bin, …).",
             {"type": "object", "properties": {"template": {"type": "string"}, "name": {"type": "string"}, "cwd": {"type": "string"}}, "required": ["template", "name"]},
             scaffold_project, "standard"),
        Tool("init_venv", "Create a Python virtual environment (.venv).",
             {"type": "object", "properties": {"path": {"type": "string"}, "python": {"type": "string"}}, "required": []},
             init_venv, "standard"),
        Tool("create_env_file", "Write a .env file + example.",
             {"type": "object", "properties": {"path": {"type": "string"}, "vars": {"type": "object"}}, "required": ["path", "vars"]},
             create_env_file, "standard"),
        Tool("create_dockerfile", "Generate a Dockerfile for a known stack.",
             {"type": "object", "properties": {"path": {"type": "string"}, "stack": {"type": "string"}}, "required": ["path", "stack"]},
             create_dockerfile, "standard"),
        Tool("create_github_workflow", "Create .github/workflows/ci.yml.",
             {"type": "object", "properties": {"path": {"type": "string"}, "provider": {"type": "string"}}, "required": ["path"]},
             create_github_workflow, "standard"),
    ]:
        r.register(t)


def _bootstrap_manual(template: str, target: Path) -> None:
    if template == "express":
        (target / "package.json").write_text(json.dumps({
            "name": target.name, "version": "0.1.0", "type": "module",
            "scripts": {"start": "node index.js", "dev": "node --watch index.js"},
            "dependencies": {"express": "^4.19.0"},
        }, indent=2))
        (target / "index.js").write_text(
            'import express from "express";\n'
            'const app = express();\n'
            'app.get("/", (req, res) => res.json({ok: true}));\n'
            'app.listen(3000, () => console.log("http://localhost:3000"));\n'
        )
    elif template == "fastapi":
        (target / "pyproject.toml").write_text(
            f'[project]\nname = "{target.name}"\nversion = "0.1.0"\n'
            'dependencies = ["fastapi>=0.115", "uvicorn[standard]>=0.30"]\n'
        )
        (target / "main.py").write_text(
            'from fastapi import FastAPI\n'
            'app = FastAPI()\n\n'
            '@app.get("/")\n'
            'def root():\n'
            '    return {"ok": True}\n'
        )
    elif template == "flask":
        (target / "pyproject.toml").write_text(
            f'[project]\nname = "{target.name}"\nversion = "0.1.0"\ndependencies = ["flask>=3.0"]\n'
        )
        (target / "app.py").write_text(
            'from flask import Flask\n'
            'app = Flask(__name__)\n\n'
            '@app.get("/")\n'
            'def root():\n'
            '    return {"ok": True}\n'
        )
    elif template == "go-mod":
        (target / "go.mod").write_text(f"module example.com/{target.name}\n\ngo 1.22\n")
        (target / "main.go").write_text(
            'package main\n\nimport "fmt"\n\nfunc main() { fmt.Println("hello") }\n'
        )


def _dockerfile_template(stack: str) -> str | None:
    t = stack.lower()
    if t in ("node", "nextjs", "express"):
        return ("FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\n"
                "EXPOSE 3000\nCMD [\"npm\", \"start\"]\n")
    if t in ("python", "fastapi", "flask", "django"):
        return ("FROM python:3.12-slim\nWORKDIR /app\nCOPY pyproject.toml ./\nRUN pip install --no-cache-dir -e .\n"
                "COPY . .\nEXPOSE 8000\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n")
    if t in ("go",):
        return ("FROM golang:1.22-alpine AS build\nWORKDIR /src\nCOPY . .\nRUN go build -o /app ./...\n\n"
                "FROM alpine:3.20\nCOPY --from=build /app /app\nEXPOSE 8080\nCMD [\"/app\"]\n")
    if t in ("rust",):
        return ("FROM rust:1.80-slim AS build\nWORKDIR /src\nCOPY . .\nRUN cargo build --release\n\n"
                "FROM debian:bookworm-slim\nCOPY --from=build /src/target/release/ /app/\nCMD [\"/app/app\"]\n")
    return None


def _gh_workflow() -> str:
    return (
        "name: ci\n"
        "on: [push, pull_request]\n"
        "jobs:\n"
        "  test:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-node@v4\n"
        "        with: { node-version: 20 }\n"
        "      - uses: actions/setup-python@v5\n"
        "        with: { python-version: '3.12' }\n"
        "      - run: if [ -f package.json ]; then npm ci && npm test --if-present; fi\n"
        "      - run: if [ -f pyproject.toml ]; then pip install -e . && pytest --if-exists || true; fi\n"
    )
